### ISSUE TITLE
Add random helper from RNGCryptoServiceProvider

### ISSUE THREAD

**Issue by Semptra** [impworks/utils#1]
Current implementation of `RandomHelper` uses `System.Random` for random number generation.
It might be useful to add a wrapper for `System.Security.Cryptography. RNGCryptoServiceProvider` class.

**Comment by impworks** [comment]
Doesn't seem to add much value. There can be lots of places in an app (game?) where pseudo-random values are used, especially when picking random elements of a predefined array. Having many places where a truly cryptographically safe random is required seems... unlikely.
